### ISSUE TITLE
Parsing infinite repeating causing invalid date

### ISSUE THREAD

**Issue by matthieudou** [pubdate/dayjs-plugin-recurring#1]
The `ISO 8601` specifications for repeating intervals specifies that the amount can be omitted or `-1`. When the amount is `-1` the parsing is failing and returning an invalid date.

```ts
// Correctly parses infinite recurring
console.log(dayjs('R/2022-01-01/P1Y').isValid()) // true

// Cannot parse infinite recurring
console.log(dayjs('R-1/2022-01-01/P1Y').isValid()) // false

// Encodes correctly with -1 notation but should maybe encode with no value ?
console.log(dayjs().recurring({start: '2022-01-01', end: '2020-01-01', duration: 'P1Y'}).recurring().toString({ dateFormat: 'YYYY-MM-DD' })) // R-1/2022-01-01/P1Y
```

Ideally, the package should be able to parse the negative value

**Comment by victortaleb** [comment]
Good catch !

https://github.com/pubdate/dayjs-plugin-recurring/pull/2 should resolve the first issue.

https://github.com/pubdate/dayjs-plugin-recurring/pull/3 should resolve the second issue.
You should not have been able to have a recurring object with start greater than end.
Do you have any use case where this would be useful ? If not, the fixes will be published tomorrow.

**Comment by matthieudou** [comment]
I don't really have use cases for that. I disable dates in the date picker, but the user can still enter the date manually. In that case, it would fall back on infinite repeating.

**Comment by victortaleb** [comment]
Version 0.1.3 has been published with these fixes.

---

It also introduces an unrelated required `order` option.
To keep the current behaviour, use `chronological`:

```js
dayjs.extend(dayjs_plugin_recurring, { order: 'chronological' })
```
